version: '3'

services:
  webdriver:
    image: robcherry/docker-chromedriver:latest
    environment:
      - CHROMEDRIVER_WHITELISTED_IPS=''
    ports:
      - "4444:4444"

  awesome-web-app:
    build: ./awesome-web-app
    ports:
      - "3333:3333"

  locust-master:
    build: ./locust
    ports:
      - "8089:8089"
    environment:
      - WEBDRIVER_SERVER=http://webdriver:4444
    volumes:
      - ./locust:/mnt/locust
    command: -f /mnt/locust/locustfiles/${LOCUSTFILE:-standard.py} --master -H http://locust-master:8089 --host ${TARGET_HOST:-https://awesome-web-app.vercel.app}

  locust-worker:
    build: ./locust
    environment:
      - WEBDRIVER_SERVER=http://webdriver:4444
    volumes:
      - ./locust:/mnt/locust
    command: -f /mnt/locust/locustfiles/${LOCUSTFILE:-standard.py} --worker --master-host locust-master
